extraction:
  cpp:
    after_prepare:
      - "mkdir $HOME/cmake-3.17 \\ \\ && wget -qO- \"https://cmake.org/files/v3.17/cmake-3.17.3-Linux-x86_64.tar.gz\"\
        \ \\ \\ | tar -xzf - --strip-components=1 -C $HOME/cmake-3.17"
      - "export PATH=$HOME/cmake-3.17/bin:$PATH"
