name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      dependencies:
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      run: echo "test echo"
      # run: |
      # echo "username ${{ inputs.username }}"
      # echo "dependencies ${{ inputs.dependencies }}"
