name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      dependencies:
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Test reusable workflow
    steps:
      - run: echo ${{ inputs.username }} ${{ inputs.dependencies }}
