name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  CI:
    uses: meintte/MyGui/.github/workflows/ci.yml@master
    with:
      os: ubuntu-latest
      dependencies: sudo apt install xorg-dev
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
