name: Windows

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  CI:
    uses: meintte/MyGui/.github/workflows/ci.yml@master
    with:
      os: windows-latest
      dependencies: echo "No dependencies"
      ENABLE_TEST_COVERAGE: 0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODACY_TOKEN: ${{ secrets.CODACY_TOKEN }}
